name: Refresh GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set GH_TOKEN
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      - name: Touch README to refresh stats
        run: |
          echo "Updating README timestamp for stats refresh" >> README.md
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Refresh GitHub stats [skip ci]" || echo "No changes"
          git push
